version: '3.1'
services:
  app:
    container_name: shopping-app
    image: shopping
    build: ./
    environment:
      - DB_HOST=dbpostgresql
      - DB_NAME=shopping
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - EMAIL=
      - PASSWORD=
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: shopping-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shopping